export const REGIONS=['서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시','세종특별자치시','경기도','강원특별자치도','충청북도','충청남도','전북특별자치도','전라남도','경상북도','경상남도','제주특별자치도'];
const aliases:Record<string,string>={"서울": "서울특별시", "부산": "부산광역시", "대구": "대구광역시", "인천": "인천광역시", "광주": "광주광역시", "대전": "대전광역시", "울산": "울산광역시", "세종": "세종특별자치시", "경기": "경기도", "강원": "강원특별자치도", "강원도": "강원특별자치도", "충북": "충청북도", "충남": "충청남도", "전북": "전북특별자치도", "전라북도": "전북특별자치도", "전남": "전라남도", "경북": "경상북도", "경남": "경상남도", "제주": "제주특별자치도", "제주도": "제주특별자치도", "서울특별시": "서울특별시", "부산광역시": "부산광역시", "대구광역시": "대구광역시", "인천광역시": "인천광역시", "광주광역시": "광주광역시", "대전광역시": "대전광역시", "울산광역시": "울산광역시", "세종특별자치시": "세종특별자치시", "경기도": "경기도", "강원특별자치도": "강원특별자치도", "충청북도": "충청북도", "충청남도": "충청남도", "전북특별자치도": "전북특별자치도", "전라남도": "전라남도", "경상북도": "경상북도", "경상남도": "경상남도", "제주특별자치도": "제주특별자치도", "세종시": "세종특별자치시"};
export const GWANGJU_DISTRICTS=['동구','서구','남구','북구','광산구'];
export const JEONNAM_DISTRICTS=['강진군','고흥군','곡성군','광양시','구례군','나주시','담양군','목포시','무안군','보성군','순천시','신안군','여수시','영광군','영암군','완도군','장성군','장흥군','진도군','함평군','해남군','화순군'];
export const MERGED_REGION_NAMES=['전남광주','광주전남','전남광주통합특별시','광주전남통합특별시'];
export function mergedAnalysisRegion(sigungu:unknown,address:unknown=''){const district=String(sigungu||'').trim().replace(/\s/g,'').replace(/^(전남광주|광주전남)/,'');const addressDistrict=String(address||'').trim().split(/\s+/)[1]||'';if(GWANGJU_DISTRICTS.some(d=>district===d||district==='광주'+d)||GWANGJU_DISTRICTS.includes(addressDistrict))return '광주광역시';if(JEONNAM_DISTRICTS.some(d=>district===d||district==='전남'+d)||JEONNAM_DISTRICTS.includes(addressDistrict))return '전라남도';return '';}
export function normalizeSido(value:unknown,address:unknown='',sigungu:unknown=''){const token=String(address||'').normalize('NFKC').trim().split(/\s+/)[0];const name=String(value||'').normalize('NFKC').trim();if(aliases[token])return aliases[token];if(MERGED_REGION_NAMES.includes(token)||MERGED_REGION_NAMES.includes(name)){const region=mergedAnalysisRegion(sigungu,address);if(region)return region;}return aliases[name]||name||'미확인';}
export const norm=(s:unknown)=>String(s??'').normalize('NFKC').toLowerCase().replace(/[\s.,()\[\]·\-]/g,'');
export const phoneNorm=(s:unknown)=>String(s??'').replace(/\D/g,'');
export function addressNorm(s:unknown){return norm(String(s??'').replace(/^(\S+)/,v=>aliases[v]||v));}
export const hospitalCategory=(value:unknown)=>{const s=String(value||'병·의원').trim();return s==='상급종합'?'상급종합병원':s;};
export function normalizeItem(x:any,kind:string){const address=String(x.addr||'');const sido=normalizeSido(x.sidoCdNm,address,x.sgguCdNm);const dong=String(x.emdongNm||'')||address.match(/(?:[\s,(])([가-힣0-9·]+(?:동|읍|면))(?=[\s,)])/u)?.[1]||'미확인';return {id:String(x.ykiho||''),name:String(x.yadmNm||''),kind,category:kind==='약국'?'약국':hospitalCategory(x.clCdNm),sido,sigungu:String(x.sgguCdNm||'미확인'),dong,address,phone:String(x.telno||''),lat:String(x.YPos||x.yPos||''),lng:String(x.XPos||x.xPos||''),name_norm:norm(x.yadmNm),address_norm:addressNorm(address),phone_norm:phoneNorm(x.telno)};}
export function candidateMatch(row:any,candidates:any[]){if(row.id){const found=candidates.filter(x=>x.id===row.id);return found.length===1?{id:found[0].id,status:'매칭 완료'}:{id:null,status:'기관번호 확인 필요'};}const exact=candidates.filter(x=>(!row.kind||x.kind===row.kind)&&((phoneNorm(row.phone).length>=8&&x.phone_norm===phoneNorm(row.phone))||(addressNorm(row.address)&&x.address_norm===addressNorm(row.address))));return exact.length===1?{id:exact[0].id,status:'매칭 완료'}:{id:null,status:exact.length>1?'중복 후보':'미매칭'};}
