import { sql } from 'drizzle-orm';
import { sqliteTable,text,integer,index,uniqueIndex,primaryKey } from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const institutions=sqliteTable('institutions',{generation:text('generation').notNull(),id:text('id').notNull(),name:text('name').notNull(),kind:text('kind').notNull(),category:text('category').notNull(),sido:text('sido').notNull(),sigungu:text('sigungu').notNull(),dong:text('dong').notNull(),address:text('address').notNull(),phone:text('phone').notNull(),lat:text('lat').notNull(),lng:text('lng').notNull(),nameNorm:text('name_norm').notNull(),addressNorm:text('address_norm').notNull(),phoneNorm:text('phone_norm').notNull()},t=>[primaryKey({columns:[t.generation,t.id]}),index('idx_inst_region').on(t.generation,t.sido,t.sigungu,t.dong),index('idx_inst_name').on(t.generation,t.nameNorm)]);
export const customers=sqliteTable('customers',{version:text('version').notNull(),row:integer('row').notNull(),name:text('name').notNull(),company:text('company').notNull(),address:text('address').notNull(),phone:text('phone').notNull(),kind:text('kind').notNull(),businessNo:text('business_no').notNull().default(''),companies:text('companies').notNull().default('[]'),duplicateCount:integer('duplicate_count').notNull().default(1),conflict:integer('conflict').notNull().default(0),sourceCodes:text('source_codes').notNull().default('[]'),sourceId:text('source_id').notNull().default(''),institutionId:text('institution_id'),status:text('status').notNull()},t=>[primaryKey({columns:[t.version,t.row]}),index('idx_custom_match').on(t.version,t.institutionId),uniqueIndex('idx_custom_business').on(t.version,t.businessNo).where(sql`${t.businessNo} <> ''`)]);

export const businessLinks=sqliteTable('business_links',{businessNo:text('business_no').primaryKey(),sourceId:text('source_id').notNull().default(''),institutionId:text('institution_id').notNull(),updatedAt:text('updated_at').notNull()});

export const institutionDepartments=sqliteTable('institution_departments',{generation:text('generation').notNull(),code:text('code').notNull(),snapshot:text('snapshot').notNull(),institutionId:text('institution_id').notNull()},t=>[primaryKey({columns:[t.generation,t.code,t.snapshot,t.institutionId]}),index('idx_department_institution').on(t.generation,t.institutionId,t.code)]);
